###TOKEN_NAMESPACE###:
    container_name: ${SERVICE_NAME}
    restart: always
    image: "${DOCKER_REGISTRY_URL}/${DOCKER_REGISTRY_REPO}/${PROJECT_NAME_KEY}:${B}"
    net: ${DOCKER_NETWORK_NAME}
    expose:
        -  "8080"
    labels:
        - "PROJECT_NAME=${PROJECT_NAME}"
        - "ENVIRONMENT_NAME=${ENVIRONMENT_NAME}"
        - "ENVIRONMENT_TYPE=java"
